name: Run Azure Terraform
description: Deploy OpenAI

inputs:
  client_id:
    description: "Azure Service Principal Client ID"
    required: true
  tenant_id:
    description: "Azure Tenant ID"
    required: true
  action:
    description: "Terraform action to run"
    required: true
    allowed_values: ["plan", "apply", "destroy"]
  subscription_id:
    description: "Azure Subscription ID for Terraform state"
    required: true
  state_resource_group:
    description: "Azure Resource Group for Terraform state"
    required: true
  state_storage_account:
    description: "Azure Storage Account for Terraform state"
    required: true
  state_container:
    description: "Azure Storage Container for Terraform state"
    default: "state"
  state_key:
    description: "Azure Storage Key for Terraform state"
    required: true
  terraform_version:
    description: "Terraform version to use"
    required: false
    default: 1.7.5
  terraform_path:
    description: "Path to Terraform configuration"
    default: "patterns/openai"

runs:
  using: composite
  steps:
    - name: Echo inputs
      shell: bash
      run: |
        echo "Client ID: ${{ inputs.client_id }}"
        echo "Tenant ID: ${{ inputs.tenant_id }}"
        echo "Action: ${{ inputs.action }}"
        echo "Subscription ID: ${{ inputs.subscription_id }}"
        echo "State Resource Group: ${{ inputs.state_resource_group }}"
        echo "State Storage Account: ${{ inputs.state_storage_account }}"
        echo "State Container: ${{ inputs.state_container }}"
        echo "State Key: ${{ inputs.state_key }}"
        echo "Terraform Version: ${{ inputs.terraform_version }}"
        echo "Terraform Path: ${{ inputs.terraform_path }}"

    - name: Terraform install
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client_id }}
        subscription-id: ${{ inputs.subscription_id }}
        tenant-id: ${{ inputs.tenant_id }}

    - name: Terraform init
      run: |
        terraform init \
          -backend-config="subscription_id=${{ inputs.state_subscription_id }}" \
          -backend-config="resource_group_name=${{ inputs.state_resource_group }}" \
          -backend-config="storage_account_name=${{ inputs.state_storage_account }}" \
          -backend-config="container_name=${{ inputs.state_container }}" \
          -backend-config="key=${{ inputs.state_key }}"
      working-directory: ${{ inputs.path }}
      shell: bash
      env:
        ARM_CLIENT_ID: ${{ inputs.client_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.subscription_id }}
        ARM_TENANT_ID: ${{ inputs.tenant_id }}
        ARM_USE_OIDC: true
        TF_IN_AUTOMATION: true
        TF_INPUT=0

    - name: Terraform ${{ inputs.action }}
      run: |
        terraform ${{ inputs.action }}
      working-directory: ${{ inputs.path }}
      shell: bash
      env:
        ARM_CLIENT_ID: ${{ inputs.client_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.subscription_id }}
        ARM_TENANT_ID: ${{ inputs.tenant_id }}
        ARM_USE_OIDC: true
        TF_IN_AUTOMATION: true
        TF_CLI_ARGS_apply: -auto-approve
        TF_CLI_ARGS_destroy: -auto-approve
        TF_INPUT=0
