name: Deploy OpenAI

on:
  workflow_call:
    inputs:
      configuration_path:
        required: true
        type: string
      action_version:
        type: string
        description: 'Github action version'
        required: true
      action:
        type: string
        description: 'Terraform action to run'
        required: true
      github_environment:
        type: string
        description: 'GitHub environment'
        required: true
      state_resource_group:
        type: string
        description: 'Azure Resource Group for Terraform state'
        required: true
      state_storage_account:
        type: string
        description: 'Azure Storage Account for Terraform state'
        required: true
      state_key:
        type: string
        description: 'Azure Storage Key for Terraform state'
        required: true
    secrets:
      client_id:
        description: 'Azure Service Principal Client ID'
        required: true
      tenant_id:
        description: 'Azure Tenant ID'
        required: true
      subscription_id:
        description: 'Azure Subscription ID for Terraform state'
        required: true

jobs:
  deploy:
    environment: ${{ inputs.github_environment }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Az CLI login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.client_id }}
        subscription-id: ${{ secrets.subscription_id }}
        tenant-id: ${{ secrets.tenant_id }}

    - name: OpenAI
      uses: rink72/terraform-library/actions/deploy-openai@v0
      with:
        client_id: ${{ secrets.client_id }}
        tenant_id: ${{ secrets.tenant_id }}
        action: ${{ inputs.action }}
        subscription_id: ${{ secrets.subscription_id }}
        state_resource_group: ${{ inputs.state_resource_group }}
        state_storage_account: ${{ inputs.state_storage_account }}
        configuration_path: ${{ github.workspace }}/${{ inputs.configuration_path }}
        state_key: ${{ github.event.repository.full_name }}/${{ inputs.state_key }}/terraform.tfstate
