name: Release library version

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  release:
    name: Release ${{ github.event.release.tag_name }} version
    runs-on: ubuntu-latest

    steps:
      - name: Update ${{ github.event.release.tag_name }} tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ github.event.release.tag_name }}
